#!/bin/bash
set -e

PLATFORM="$(uname -s)"
KUBERNETES_VERSION=${KUBERNETES_VERSION:-0.11.0}
[[ "${KUBERNETES_VERSION}" == "latest" ]] && \
  KUBERNETES_VERSION=$(curl --insecure -sS https://get.k8s.io | grep release= | sed -e 's,.*=v,,')

KUB_URL="https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_VERSION}/bin/$( \
  echo ${PLATFORM} | tr '[:upper:]' '[:lower:]')/amd64/kubectl"

scream () {
    cat <<< "$@" 1>&2
    exit 1
}

case "$PLATFORM" in
  Darwin)
    targetDir="/usr/local/bin"
    ;;
  Linux)
    # targetDir="/opt/bin"
    targetDir="/usr/local/bin"
    ;;
  *)
    scream "Unknown or unsupported platform: ${PLATFORM}"
    ;;
esac

if [[ "$#" -eq 1 && "$1" == "install"  ]] ; then
  echo "Downloading and installing ${PLATFORM} version of kubectl (Kubernetes CLI) into ${targetDir}. This may take a couple minutes, depending on your internet speed.."
  [ -d ${targetDir} ] || sudo mkdir -p ${targetDir}
  [ -f ${targetDir}/kubectl ] || sudo wget -q -L -O ${targetDir}/kubectl "${KUB_URL}"
  [ -x ${targetDir}/kubectl ] || sudo chmod +x ${targetDir}/kubectl
elif [[ "$#" -eq 1 && "$1" == "uninstall"  ]] ; then
  [ -f ${targetDir}/kubectl ] && sudo rm -f ${targetDir}/kubectl
elif [[ "$#" -eq 1 && "$1" == "shellinit"  ]] ; then
  if [[ ! -f ${targetDir}/kubectl ]]; then
    echo "echo 'kubectl' (kubernetes cli) wasn't found in your \$PATH."
    echo "Run './kubLocalSetup install' first."
    scream
  fi
  echo "export ETCDCTL_PEERS=http://172.17.8.101:4001"
  echo "export FLEETCTL_ENDPOINT=http://172.17.8.101:4001"
  echo "export KUBERNETES_MASTER=http://172.17.8.101:8080"
else
  echo "Usage: ./kubLocalSetup (install|shellinit|unistall)"
fi

