#cloud-config

---
write-files:
  - path: /etc/conf.d/nfs
    permissions: '0644'
    content: |
      OPTS_RPC_MOUNTD=""
  - path: /opt/bin/wupiao
    permissions: '0755'
    content: |
      #!/bin/bash
      # [w]ait [u]ntil [p]ort [i]s [a]ctually [o]pen
      [ -n "$1" ] && \
        until curl -o /dev/null -sIf http://${1}; do \
          sleep 1 && echo .;
        done;
      exit $?

coreos:
  etcd2:
    name: __NAME__
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    advertise-client-urls: http://$public_ipv4:2379,http://$public_ipv4:4001
    initial-cluster-token: k8s_etcd
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
    initial-advertise-peer-urls: http://$private_ipv4:2380
    initial-cluster: __ETCD_SEED_CLUSTER__
    initial-cluster-state: new
  fleet:
    public-ip: $public_ipv4
    metadata: "role=master"
  flannel:
    interface: $public_ipv4
  units:
    - name: rpcbind.service
      enable: true
      command: start
    - name: rpc-statd.service
      enable: true
      command: start
    - name: docker-cache.service
      command: start
      content: |
        [Unit]
        Description=Docker cache proxy
        Requires=early-docker.service
        After=early-docker.service
        Before=early-docker.target
        [Service]
        Restart=always
        TimeoutStartSec=0
        RestartSec=5
        Environment="TMPDIR=/var/tmp/"
        Environment="DOCKER_HOST=unix:///var/run/early-docker.sock"
        ExecStartPre=-/usr/bin/docker kill docker-registry
        ExecStartPre=-/usr/bin/docker rm docker-registry
        ExecStartPre=/usr/bin/docker pull quay.io/devops/docker-registry:latest
        # GUNICORN_OPTS is an workaround for
        # https://github.com/docker/docker-registry/issues/892
        ExecStart=/usr/bin/docker run --rm --net host --name docker-registry \
          -e STANDALONE=false \
          -e GUNICORN_OPTS=[--preload] \
          -e MIRROR_SOURCE=https://registry-1.docker.io \
          -e MIRROR_SOURCE_INDEX=https://index.docker.io \
          -e MIRROR_TAGS_CACHE_TTL=1800 \
          __PROXY_LINE__-e HTTP_PROXY=__HTTP_PROXY__ \
          __PROXY_LINE__-e HTTPS_PROXY=__HTTPS_PROXY__ \
          __PROXY_LINE__-e NO_PROXY=__NO_PROXY__ \
          quay.io/devops/docker-registry:latest
    - name: fleet.service
      command: start
    - name: flanneld.service
      command: start
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Unit]
            Requires=etcd2.service
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.244.0.0/16", "Backend": {"Type": "host-gw"}}'
    - name: docker.service
      command: start
      drop-ins:
        - name: 51-docker-mirror.conf
        - __PROXY_LINE__name: http-proxy.conf
          __PROXY_LINE__content: |
            __PROXY_LINE__[Service]
            __PROXY_LINE__EnvironmentFile=/etc/environment
    - name: early-docker.service
      drop-ins:
        - __PROXY_LINE__name: http-proxy.conf
          __PROXY_LINE__content: |
            __PROXY_LINE__[Service]
            __PROXY_LINE__EnvironmentFile=/etc/environment
    - name: kube-install.service
      command: start
      content: |
        [Unit]
        Description=Download/Install Kubernetes
        Requires=network-online.target kube-certs.service
        After=network-online.target kube-certs.service
        ConditionPathExists=/srv/kubernetes
        ConditionPathExists=!/opt/bin/kube-apiserver
        ConditionPathExists=!/opt/bin/kube-controller-manager
        ConditionPathExists=!/opt/bin/kube-scheduler
        [Service]
        Type=oneshot
        EnvironmentFile=/etc/environment
        ExecStart=-/usr/bin/mkdir -p /opt/bin
        ExecStart=/usr/bin/wget -P /opt/bin https://storage.googleapis.com/kubernetes-release/release/__RELEASE__/bin/linux/amd64/kube-apiserver
        ExecStart=/usr/bin/wget -P /opt/bin https://storage.googleapis.com/kubernetes-release/release/__RELEASE__/bin/linux/amd64/kube-controller-manager
        ExecStart=/usr/bin/wget -P /opt/bin https://storage.googleapis.com/kubernetes-release/release/__RELEASE__/bin/linux/amd64/kube-scheduler
        ExecStart=/usr/bin/chmod +x /opt/bin/kube-apiserver
        ExecStart=/usr/bin/chmod +x /opt/bin/kube-controller-manager
        ExecStart=/usr/bin/chmod +x /opt/bin/kube-scheduler
    - name: kube-certs.service
      command: start
      content: |
        [Unit]
        Description=Generate Kubernetes API Server certificates
        ConditionPathExists=/tmp/make-certs.sh
        Requires=network-online.target
        After=network-online.target
        [Service]
        ExecStartPre=-/usr/sbin/groupadd -r kube-cert
        ExecStartPre=/usr/bin/chmod 755 /tmp/make-certs.sh
        ExecStart=/tmp/make-certs.sh $public_ipv4 IP:$public_ipv4,IP:10.100.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.__DNS_DOMAIN__
        Type=oneshot
        RemainAfterExit=true
    - name: kube-apiserver.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes API Server
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=etcd2.service docker-cache.service fleet.service docker.service flanneld.service kube-install.service
        After=etcd2.service docker-cache.service fleet.service docker.service flanneld.service kube-install.service
        [Service]
        ExecStartPre=/opt/bin/wupiao $private_ipv4:2379/v2/machines
        ExecStart=/opt/bin/kube-apiserver \
          --client-ca-file=/srv/kubernetes/ca.crt \
          --tls-cert-file=/srv/kubernetes/server.cert \
          --tls-private-key-file=/srv/kubernetes/server.key \
          --admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota \
          --service_account_key_file=/srv/kubernetes/server.key \
          --service_account_lookup=false \
          --allow_privileged=true \
          --insecure_bind_address=0.0.0.0 \
          --insecure_port=8080 \
          --kubelet_https=true \
          --secure_port=6443 \
          --service-cluster-ip-range=10.100.0.0/16 \
          --etcd_servers=http://$private_ipv4:2379 \
          --bind-address=$public_ipv4 \
          --cloud_provider=__CLOUDPROVIDER__ \
          --logtostderr=true \
          --runtime_config=api/v1
        Restart=always
        RestartSec=10
    - name: kube-controller-manager.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Controller Manager
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=kube-apiserver.service
        After=kube-apiserver.service
        [Service]
        ExecStartPre=/opt/bin/wupiao $private_ipv4:8080
        ExecStart=/opt/bin/kube-controller-manager \
          --root-ca-file=/srv/kubernetes/ca.crt \
          --service-account-private-key-file=/srv/kubernetes/server.key \
          --master=$private_ipv4:8080 \
          --cloud_provider=__CLOUDPROVIDER__ \
          --pod_eviction_timeout=30s \
          --logtostderr=true
        Restart=always
        RestartSec=10
    - name: kube-scheduler.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Scheduler
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=kube-apiserver.service
        After=kube-apiserver.service
        [Service]
        ExecStartPre=/opt/bin/wupiao $private_ipv4:8080
        ExecStart=/opt/bin/kube-scheduler \
          --master=$private_ipv4:8080
        Restart=always
        RestartSec=10
  update:
    group: __CHANNEL__
    reboot-strategy: off
